server:
  port: 8081

spring:
  application:
    name: demo

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/auth-db}

jwt:
  secret: {}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000


