server:
  port: 8084

spring:
  application:
    name: favourite-service

  data:
    mongodb:
      uri: ${FAVOURITE_MONGO_URI:mongodb://localhost:27017/favourite-db}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
