server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**

        - id: dealer-service
          uri: http://dealer-service:8082
          predicates:
            - Path=/api/dealer/**

        - id: car-service
          uri: http://car-service:8083
          predicates:
            - Path=/api/cars/**

        - id: favourite-service
          uri: http://favourite-service:8084
          predicates:
            - Path=/api/favourites/**

jwt:
  secret: ${JWT_SECRET}